name: fontra # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1.dev11247+g4c06458' # just for humans, typically '1.2+git' or '1.3.2'
summary: Browser-based variable-first font editor # 79 char long summary
description: |
  Fontra is an open-source, browser-based, cross-platform, variable-first font editor.
  Fontra extends the boundaries of what current font editors can do. Originally 
  developed to make the design and production of large CJK fonts more efficient,
   Fontra provides deeper integration of variable font technology and improved
  usability of variable components as design elements.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
parts:
  Fontra-pak:
    plugin: dump
    source: .
    stage-packages:
        

apps:
  Fontra-Pak:
    command: FontraPak
    plugs:
      - home
      - media
      - network
